# config.yaml
ragflow:
  api:
    url: "http://localhost:8081"
    key: "ragflow-A1ODAxNjdhZjdkMzExZWY5NTkxMDI0Mm"
  knowledge_base:
    default_name: "user_knowledge_base"
    embedding_model: "bge-m3"
  
  chunk_settings:
    method: "naive"
    chunk_size: 128
    delimiter: "\\n!?;。；！？"
    layout_recognize: True
    raptor: True
    embedding_model: "BAAI/bge-large-zh-v1.5"

  retrieval:
    top_k: 1024    # 送入rerank模型的块数
    top_n: 3       # 返回给大模型的块数
    similarity_threshold: 0.2
    vector_similarity_weight: 0.3
    rerank_id: "BAAI/bge-reranker-v2-m3"
    keyword: false
    prompt: |
      你是一个智能助手，请总结知识库的内容来回答问题，回答需要考虑聊天历史。
      当无法从知识库中找到答案时，你的回答必须包含“知识库中未找到您要的答案！”。
      
      以下是知识库：
      {knowledge}


model:
  local:
    name: "deepseek-r1:14b"
    ollama_url: "http://172.16.49.9:11434"
  cloud:
    name: "deepseek-r1-distill-llama-14b"
    api_key: ""
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  siliconflow: 
    url: "https://api.siliconflow.cn/v1/models"
    api_key: "sk-dtcvqqclowpyohjskwebkbxcsokfjuvathgponlfvcumqsij"

file:
  upload_dir: "RAGKnowledgeFiles/"
  allowed_ext:
    - "pdf"
    - "docx"
    - "txt"
    - "md"
    - "html"
    - "csv"
    - "pptx"
    - "xlsx"
  parser:
    ocr_langs: ["chi_sim", "eng"]
    extract_tables: true

database:
  host: 172.16.49.81:3306
  username: "root"
  password: "root"
  llm: "deepseek-r1:14b"
  db_name: "shh-safety-monitor-his"

  rag_flow_mysql_host: localhost
  rag_flow_mysql_port: 5455
  rag_flow_mysql_username: "root"
  rag_flow_mysql_password: "infini_rag_flow"
  rag_flow_mysql_db_name: "rag_flow"

  redis_url: localhost:6379/0
  redis_pwd: "infini_rag_flow"


system:
  debug: true
  max_file_size: 104857600  # 100MB in bytes
  session_timeout: 3600